### ISSUE TITLE
Team background for marketing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/connect5#1]
To help promote the Tech for Better programme and this first graduate project, it would be great to get a short background on each of the team members. 

Can everyone please comment on this issue, providing short answers to each of these points:

## What excites you about working on Tech for Better?

It can be very informal and doesn't have to be long (no more than 100 words per point).

**Comment by RamyAlshurafa** [comment]
## A brief background on who you are:

My name's **Ramy Al Shurafa**; I am 26 years old. I was born in Gaza-Palestine. I attended Islamic University - Gaza. First, I studied Science for 2 years. Then, I studied Mechanical Engineering for one semester. After that, I studied Civil Engineering.
I graduated as a Civil Engineer then I received the Surveying and GIS Diploma. I worked for 2 years in these two fields.

## How did you get into coding?

Since previously I did not know much about coding or computer science, I never thought of it as an interest of mine. I studied 3 programs while at the University. When I studied MATLAB for my Engineering major, I found it very interesting and attracted me to the field. 

After I graduated, I was not satisfied with my jobs; after 2 years, I decided to go back to University and study Computer Engineering. Fortunately, I saw a post on Facebook for applications to the 4th cohort I GazaSkyGeeks, so I decided to apply. and I began coding.
## What made you join Founders & Coders?

I didn't hear about Founders and Coders before I enrolled in GazaSkyGeeks. However, I have found that it is a really amazing and exciting community. It changed my whole life forever. I was able to meet and work with some very talented developers. This experience has really sharpened my coding and personal skills.

## What excites you about working on Tech for Better?

I applied to work on Tech for Better so that I can have the opportunity to improve my technical skills. Working with remote clients and remote developers are invaluable experiences that will allow me to see how other developers think and to learn new techniques.

**Comment by dupreesi** [comment]
## A brief background on who you are:

Hi I’m Simon, 31 years old from Germany. I grew up in a lovely Bavarian village called Kirchehrenbach but moved to Berlin to study and start a semi-professional DJ career :)

## How did you get into coding?

While studying Natural Resource Management I was enrolled in some Geographic Information System courses involving some basic Python scripting. Later I made a couple of websites for own projects and later for other clients and really enjoyed it! After graduating from Uni I also worked as an environmental data scientist which meant that I had to collaborate with software developers to put our case study work into small Apps. Thats when I realised - I need to change careers!
What made you join Founders & Coders?
I’ve heard about FAC because a friend was doing the program beforehand. He told me about FAC’s visions and ethics and I was blown away by the relation of coding and social impact and software development as a team based activity.

## What excites you about working on Tech for Better?

Having studied politics, economics and natural resource management I found myself being very conscious about the importance of improving social and environmental conditions. One of the most effective ways towards sustainable, positive change is the use of technology. Having recently graduated from Founders and Coders I am very eager to use my software development skills within the Tech for Better programme. I am sure that together we can make huge impact and I am very excited about the chance to work together with like minded developers in Gaza and the UK.

**Comment by thejoefriel** [comment]
## A brief background on who you are:

Hi. My name's Joe, 31 years old from London. Before joining Founders & Coders and becoming a developer, I spent the past 9 years working in children's media and then digital advertising. 

## How did you get into coding?

Through my career I've worked on digital brands, from copywriting when I first started work through to leading the innovation and creation of a platform that would enable brands to identify and track influencers and then manage influencer campaigns. Throughout all of this I've worked closely with developers and always generally found myself more interested in what they were doing than my own work! 

I was increasingly doing coding on the side, working on little projects, and after reaching a certain level in my career at that time and not really being fulfilled, I realised that it was time to take the plunge!

## What excites you about working on Tech for Better?

Having spent most of my career working where technology and young people intersect, I have seen first hand how powerful and increasingly integral a role technology plays in our lives. However, technology itself is amoral – it is up to us to use it in a responsible way that will help drive positive, sustainable change. Tech for Better is a truly unique and fantastic opportunity that connects like-minded developers – across the UK and Gaza – with people looking to address important social issues, to bring to life solutions through technology that can deliver real impact.  I am so excited to have the opportunity to be a part of Tech for Better and help it to continue to grow so we can help many more non-profits in the future.

**Comment by marwajomaa** [comment]
## A brief background on who you are:
Hi, my name's Marwa, I am 25 years old. I am a graduate from fourth cohort code academy at Gaza sky geeks and founder&coders. Now I ’m a Javascript web developer after six months of training and working on projects for the tech community at GSG.

## How did you get into coding?
 What motivated me to be a programmer is that I didn’t find the passion I was looking for in my specialization
, as I studied chemistry at university while I was interested in software engineering but I wasn't destined to study that specialty even though I had a grade that enabled me to enter. After graduation I decided to learn about programming myself, I was enrolled in online programming courses and I enjoyed it a lot and then I found the code academy at Gaza Sky Geeks by accident from an ad on facebook and since then I have found myself in the right place.

## What made you join Founders & Coders?
I knew founders & coders after joining GSG and I didn't know it before, since then I discovered this amazing community, which includes people from around the world sharing the same goal and interest which I really benefit from them a lot.

## What excites you about working on Tech for Better?
The thing that made me like programming is that it doesn't believe in boundaries and constraints, while it enables me from home to communicate with people from different parts of the world, and this is my dream, which I found in Tech for better, where I can communicate and work with talented developers and clients remotely, share ideas and do great work  as if we are in the same place. Also to have the chance to enhance my technical and communications skills, so I think I'm lucky to be a part of this community as I'm looking for working with such talented developers from the UK.
