### ISSUE TITLE
Agree on Gitflow

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#42]
Here is a quick guide for gitflow, that we worked on before.

## Issues 
1. Starting with **User Journey**:
  - start the planning with making User journey for potential users for your project.
  - list the acceptance criteria for that journey (every criterion will be a user story after that).
  - add user `journey` and `epic` labels to the issue.

 2. Create an issue for each user story.
  - each user story has acceptance criteria.
  - link the user story with related user journey.
  - add `user story` and `epic` labels to the issue.
  - each user story may lead to one or more task issue.

3. Create a Sprint.
  - create sprint planning as a milestone
  - add some description for that milestone.
  - select sprint end date.
  - add user stories issue sprints.

4. Create an issue for each task.
  - every task may should include a description of how this task would perform.
  - link the task issue with related user story/ies.
  - add `task` label, and time label eg `T4h`any grouping label eg. `front-end`, `back-end`, `sprint-1`
  - add priority label.
  - each task will lead to one PR.

## Pull Requests:
1. Each developer must be assigned to one active PR.
  - every developer should assign his/herself to one task issue.
  - add `in progress` label to that issue.
  - at the end of each day the push your work on that PR.
     - If the PR is ready: add `awaiting review` label.
     - assign yourself to that issue.
    - request review from your team (QA if someone join us) to review it.
    - If two developers (maybe one) approved that PR you can merge.
    - close the issues that done by that PR.

2. Reviewing PRs:
 If any developer request your review for a PR
  - Remove `awaiting review` label and add `in review` while you are reviewing the PR.
  - If you approved the PR remove `in review` and add `approved`
  - if you need some changes for that PR remove `in review` and add `request changes`

@arrested-developer @thejoefriel @dupreesi @marwajomaa  @thejoefriel What do you think about this, it's still a suggestion.
What do you think?

**Comment by thejoefriel** [comment]
This is great! Definitely happy to follow a lot of this.

Agree with Michael on the user stories not always being epics. I think a number of the user stories we've created may be achievable as issues, rather than needing to break down even more. Maybe we approach each on a case by case, and if you feel that you would like that particular issue broken down into task issues then we can?

I've edited all the issues, added a few more, given them labels and very rough suggested timings. I've created a milestone for our core sprint and added all the relevant issues to this and then broken them down into priority 2 and priority 3 items so it's hopefully very clear which ones we should tackle first. 

@RamyAlshurafa @marwajomaa did you want to have a look and let me know if this looks ok for you?

**Comment by RamyAlshurafa** [comment]
@arrested-developer 
As we worked before, even though the user is small, it will be splitted into front-end and back-end task.
But in our case ( each one will take the front and back task) the user story can be a task and user story at the same time

**Comment by RamyAlshurafa** [comment]
That's great, @thejoefriel  Thank you

> and if you feel that you would like that particular issue broken down into task issues then we can?

I agree :+1:
