### ISSUE TITLE
Bug: train the trainers sessions don't show the rest of the questions

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#624]
while filling the train the trainers surveys and after answering the first group of questions (demographic), I can't continue to the next group

**Comment by dupreesi** [comment]
the error occurs because after filling in demographic data the next section is set to be behavioural insights rather than about your usual way of teaching

<img width="473" alt="Bildschirmfoto 2019-10-11 um 10 32 37" src="https://user-images.githubusercontent.com/23721486/66637030-941ce980-ec12-11e9-959e-fe9bc29b6ff9.png">
